### ISSUE TITLE
Gitignore .idea folder.

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/atlas-wrapper#1]
@jmtsuji 

The ```.idea``` folder is created by Pycharm/Intellij. Its probably a good idea not version control this stuff since its just per project setting files for Intellij. You should gitignore the folder.

Tutorial here: https://docs.microsoft.com/en-us/vsts/git/tutorial/ignore-files?tabs=visual-studio#tabpanel_RjDz0tPtiY_visual-studio

Here is an example: https://github.com/Metannotate/Metannotate/blob/master/.gitignore

Note:

You will have to remove these files from Git tracking first before ignoring them (if you add them to gitignore before you won't be able to remove them because git won't be able to see them).

**Comment by LeeBergstrand** [comment]
Addressed in https://github.com/jmtsuji/atlas-wrapper/pull/2

**Comment by jmtsuji** [comment]
Now updated by merging your pull request -- thanks for the tip.
